# -*- coding: utf-8 -*-
"""NOP phase 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vm5ausEUf7XsTS_86ujE9ENUSgJG2uj5
"""

from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# -------------------------------
# DATASET
# -------------------------------
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()
X = data.data
y = data.target

print("Dataset shape:", X.shape)

# Add bias term
X = np.c_[np.ones(X.shape[0]), X]

# -------------------------------
# SIGMOID
# -------------------------------
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# -------------------------------
# LOGISTIC LOSS + GRADIENT
# -------------------------------
def log_loss(w, X, y):
    z = X @ w
    return -np.mean(y*np.log(sigmoid(z)) + (1-y)*np.log(1 - sigmoid(z)))

def log_gradient(w, X, y):
    z = X @ w
    return X.T @ (sigmoid(z) - y) / len(y)

def log_hessian(w, X):
    z = X @ w
    S = np.diag(sigmoid(z) * (1 - sigmoid(z)))
    return X.T @ S @ X / len(z)

# -------------------------------
# GRADIENT DESCENT
# -------------------------------
def gradient_descent_log(X, y, lr=0.1, iterations=100):
    w = np.zeros(X.shape[1])
    history = []

    for _ in range(iterations):
        grad = log_gradient(w, X, y)
        w -= lr * grad
        history.append(log_loss(w, X, y))

    return w, history

# -------------------------------
# NEWTON METHOD
# -------------------------------
def newton_log(X, y, iterations=10):
    w = np.zeros(X.shape[1])
    history = []

    for _ in range(iterations):
        grad = log_gradient(w, X, y)
        hess = log_hessian(w, X)
        w -= np.linalg.inv(hess) @ grad
        history.append(log_loss(w, X, y))

    return w, history

# -------------------------------
# TRAIN MODELS
# -------------------------------
start = time.time()
w_gd, hist_gd = gradient_descent_log(X, y)
gd_time = time.time() - start

start = time.time()
w_newton, hist_newton = newton_log(X, y)
newton_time = time.time() - start

# Predictions
y_pred_gd = sigmoid(X @ w_gd) >= 0.5
y_pred_newton = sigmoid(X @ w_newton) >= 0.5

# -------------------------------
# BASELINE MODELS
# -------------------------------
sk_log = LogisticRegression()
sk_log.fit(X[:,1:], y)
y_pred_sk = sk_log.predict(X[:,1:])

svm = SVC()
svm.fit(X[:,1:], y)
y_pred_svm = svm.predict(X[:,1:])

# -------------------------------
# EVALUATION
# -------------------------------
def evaluate(y_true, y_pred):
    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred),
        "Recall": recall_score(y_true, y_pred),
        "F1": f1_score(y_true, y_pred)
    }

results_ml = pd.DataFrame([
    ["GD Logistic", *evaluate(y, y_pred_gd).values(), gd_time],
    ["Newton Logistic", *evaluate(y, y_pred_newton).values(), newton_time],
    ["Sklearn Logistic", *evaluate(y, y_pred_sk).values(), 0],
    ["SVM", *evaluate(y, y_pred_svm).values(), 0]
], columns=["Model","Accuracy","Precision","Recall","F1","Time"])

print("\nML Model Comparison:")
print(results_ml)

# -------------------------------
# PLOTS
# -------------------------------
plt.plot(hist_gd, label="GD Loss")
plt.plot(hist_newton, label="Newton Loss")
plt.title("Logistic Regression Loss Convergence")
plt.xlabel("Iterations")
plt.ylabel("Loss")
plt.legend()
plt.show()